"""Tenant-scoped municipal service foundation."""
from alembic import op

revision = "0001_platform_foundation"
down_revision = None
branch_labels = None
depends_on = None

DDL = [
"CREATE EXTENSION IF NOT EXISTS pgcrypto",
"CREATE EXTENSION IF NOT EXISTS postgis",
"CREATE TABLE organizations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), parent_id uuid REFERENCES organizations(id), kind text NOT NULL CHECK(kind IN ('DISTRICT','TALUKA','MUNICIPALITY')), slug text NOT NULL UNIQUE, name jsonb NOT NULL, status text NOT NULL DEFAULT 'ACTIVE', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE wards (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, name jsonb NOT NULL, boundary geometry(MultiPolygon,4326), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,code))",
"CREATE TABLE departments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), name jsonb NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), phone_e164 text, email text, password_hash text, status text NOT NULL DEFAULT 'PENDING', locale text NOT NULL DEFAULT 'mr', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,phone_e164), CHECK(phone_e164 IS NOT NULL OR email IS NOT NULL))",
"CREATE TABLE roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), code text NOT NULL, name text NOT NULL, UNIQUE(organization_id,code))",
"CREATE TABLE permissions (code text PRIMARY KEY, description text NOT NULL)",
"CREATE TABLE user_roles (user_id uuid NOT NULL REFERENCES users(id), role_id uuid NOT NULL REFERENCES roles(id), ward_id uuid REFERENCES wards(id), department_id uuid REFERENCES departments(id), granted_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,role_id,ward_id,department_id))",
"CREATE TABLE households (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), ward_id uuid NOT NULL REFERENCES wards(id), household_no text NOT NULL, address jsonb NOT NULL, verification_status text NOT NULL DEFAULT 'UNVERIFIED', classification text NOT NULL DEFAULT 'RESTRICTED', created_by uuid REFERENCES users(id), updated_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,household_no))",
"CREATE TABLE citizens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid REFERENCES users(id), household_id uuid REFERENCES households(id), full_name jsonb NOT NULL, mobile_e164 text, date_of_birth date, profile_photo_key text, consent_version text, verified_at timestamptz, created_by uuid REFERENCES users(id), updated_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE family_memberships (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), household_id uuid NOT NULL REFERENCES households(id), citizen_id uuid NOT NULL REFERENCES citizens(id), relationship_code text NOT NULL, valid_from date NOT NULL DEFAULT CURRENT_DATE, valid_to date, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(household_id,citizen_id,valid_from))",
"CREATE TABLE complaint_categories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, label jsonb NOT NULL, department_id uuid REFERENCES departments(id), active boolean NOT NULL DEFAULT true, UNIQUE(organization_id,code))",
"CREATE TABLE complaints (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), public_id text NOT NULL, citizen_id uuid REFERENCES citizens(id), ward_id uuid NOT NULL REFERENCES wards(id), category_id uuid NOT NULL REFERENCES complaint_categories(id), department_id uuid REFERENCES departments(id), assigned_to uuid REFERENCES users(id), title text NOT NULL, description text NOT NULL, status text NOT NULL DEFAULT 'SUBMITTED' CHECK(status IN ('SUBMITTED','ACKNOWLEDGED','ASSIGNED','IN_PROGRESS','WAITING_FOR_INFORMATION','RESOLVED','REJECTED','REOPENED','CLOSED')), priority text NOT NULL DEFAULT 'NORMAL' CHECK(priority IN ('LOW','NORMAL','HIGH','EMERGENCY')), location geography(Point,4326), anonymous boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,public_id))",
"CREATE TABLE complaint_status_history (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), complaint_id uuid NOT NULL REFERENCES complaints(id), from_status text, to_status text NOT NULL, actor_id uuid REFERENCES users(id), note text, created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE complaint_attachments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), complaint_id uuid NOT NULL REFERENCES complaints(id), object_key text NOT NULL, media_type text NOT NULL, scan_status text NOT NULL DEFAULT 'PENDING', created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE complaint_comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), complaint_id uuid NOT NULL REFERENCES complaints(id), author_id uuid REFERENCES users(id), body text NOT NULL, visibility text NOT NULL DEFAULT 'CITIZEN_VISIBLE', created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE announcements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), ward_id uuid REFERENCES wards(id), title jsonb NOT NULL, body jsonb NOT NULL, kind text NOT NULL, state text NOT NULL DEFAULT 'DRAFT', approved_by uuid REFERENCES users(id), published_at timestamptz, created_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), title jsonb NOT NULL, classification text NOT NULL, object_key text NOT NULL, version integer NOT NULL DEFAULT 1, metadata jsonb NOT NULL DEFAULT '{}', uploaded_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE services (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), code text NOT NULL, title jsonb NOT NULL, details jsonb NOT NULL, department_id uuid REFERENCES departments(id), workflow_mode text NOT NULL DEFAULT 'REQUEST', published boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,code))",
"CREATE TABLE service_applications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), service_id uuid NOT NULL REFERENCES services(id), citizen_id uuid NOT NULL REFERENCES citizens(id), status text NOT NULL DEFAULT 'SUBMITTED', payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE payments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), application_id uuid REFERENCES service_applications(id), citizen_id uuid NOT NULL REFERENCES citizens(id), provider text NOT NULL, provider_transaction_id text, amount_minor bigint NOT NULL CHECK(amount_minor >= 0), currency char(3) NOT NULL DEFAULT 'INR', status text NOT NULL, receipt_reference text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE government_schemes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), title jsonb NOT NULL, eligibility jsonb NOT NULL, source_url text, deadline date, state text NOT NULL DEFAULT 'DRAFT', approved_by uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), ward_id uuid REFERENCES wards(id), department_id uuid REFERENCES departments(id), title jsonb NOT NULL, public_phone text, public_email text, approved boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE emergency_contacts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), category text NOT NULL, display_name jsonb NOT NULL, official_number text NOT NULL, verified_source text NOT NULL, verified_at timestamptz NOT NULL, active boolean NOT NULL DEFAULT false, approved_by uuid REFERENCES users(id))",
"CREATE TABLE field_visits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), complaint_id uuid NOT NULL REFERENCES complaints(id), officer_id uuid NOT NULL REFERENCES users(id), action text NOT NULL, notes text, gps geography(Point,4326), gps_policy_version text, occurred_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE feedback (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), complaint_id uuid NOT NULL REFERENCES complaints(id), citizen_id uuid REFERENCES citizens(id), rating smallint NOT NULL CHECK(rating BETWEEN 1 AND 5), comment text, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(complaint_id,citizen_id))",
"CREATE TABLE notifications (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid NOT NULL REFERENCES users(id), channel text NOT NULL, template_code text NOT NULL, status text NOT NULL DEFAULT 'QUEUED', payload jsonb NOT NULL DEFAULT '{}', sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_id uuid, action text NOT NULL, resource_type text NOT NULL, resource_id uuid, before_value jsonb, after_value jsonb, request_id text, created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE ai_interactions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), actor_id uuid, purpose text NOT NULL, provider text NOT NULL, redaction_applied boolean NOT NULL, source_refs jsonb NOT NULL DEFAULT '[]', output jsonb, human_review_state text NOT NULL DEFAULT 'NOT_REQUIRED', created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE security_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid REFERENCES organizations(id), event_type text NOT NULL, severity text NOT NULL, actor_id uuid, request_id text, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now())",
"CREATE TABLE import_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES organizations(id), submitted_by uuid NOT NULL REFERENCES users(id), object_key text NOT NULL, status text NOT NULL DEFAULT 'UPLOADED', validation_summary jsonb, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz)",
"CREATE INDEX ix_wards_org ON wards(organization_id)",
"CREATE INDEX ix_households_org_ward ON households(organization_id,ward_id)",
"CREATE INDEX ix_citizens_org_household ON citizens(organization_id,household_id)",
"CREATE INDEX ix_complaints_org_ward_status ON complaints(organization_id,ward_id,status,created_at DESC)",
"CREATE INDEX ix_complaints_org_category ON complaints(organization_id,category_id,created_at DESC)",
"CREATE INDEX ix_complaints_geo ON complaints USING gist(location)",
"CREATE INDEX ix_audit_org_created ON audit_logs(organization_id,created_at DESC)",
"CREATE INDEX ix_notifications_user_status ON notifications(user_id,status,created_at DESC)",
"DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['wards','departments','users','households','citizens','family_memberships','complaint_categories','complaints','complaint_status_history','complaint_attachments','complaint_comments','announcements','documents','services','service_applications','payments','government_schemes','contacts','emergency_contacts','field_visits','feedback','notifications','audit_logs','ai_interactions','import_jobs'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (organization_id = nullif(current_setting(''app.organization_id'', true), '''')::uuid) WITH CHECK (organization_id = nullif(current_setting(''app.organization_id'', true), '''')::uuid)', t); END LOOP; END $$",
"CREATE OR REPLACE FUNCTION deny_audit_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'audit rows are append-only'; END $$",
"CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION deny_audit_mutation()",
]

def upgrade():
    for statement in DDL:
        op.execute(statement)

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS audit_immutable ON audit_logs")
    for table in ["import_jobs", "security_events", "ai_interactions", "audit_logs", "notifications", "feedback", "field_visits", "emergency_contacts", "contacts", "government_schemes", "payments", "service_applications", "services", "documents", "announcements", "complaint_comments", "complaint_attachments", "complaint_status_history", "complaints", "complaint_categories", "family_memberships", "citizens", "households", "user_roles", "permissions", "roles", "users", "departments", "wards", "organizations"]:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    op.execute("DROP FUNCTION IF EXISTS deny_audit_mutation()")
