{{- if and .Values.database.createSecret .Values.database.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "microservice-showcase.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.connectionStringKey }}: {{ .Values.database.connectionString | quote }}
{{- end }}

