{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "microservice-showcase.fullname" . }}-backend
  labels:
    {{- include "microservice-showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "microservice-showcase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
{{- end }}

